development:
  adapter: mysql2
  username: root
  database: sudoku_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: sudoku_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  username: root
  database: sudoku_production
  pool: 5
  timeout: 5000
